# Tomcat
server:
    tomcat:
      uri-encoding: UTF-8
      threads:
        max: 1000
        min-spare: 30
    port: 80
#    servlet:
#        context-path: /wx

debug: false

spring:
    profiles:
        active: @profile.active@ #此处由maven的环境选择决定，参考：https://www.jianshu.com/p/b7c75b0c364c
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    mvc:
        throw-exception-if-no-handler-found: true
    task:
        scheduling:
            pool:
                size: 5


#mybatis
mybatis-plus:
    mapper-locations: classpath*:/mapper/**/*.xml
    #实体扫描，多个package用逗号或者分号分隔
    type-aliases-package: com.github.niefy.modules.*.entity
    type-handlers-package: com.github.niefy.common.handler
    global-config:
        #数据库相关配置
        db-config:
            #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
            id-type: AUTO
            logic-delete-value: -1
            logic-not-delete-value: 0
        banner: false
    #原生配置
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: false
        call-setters-on-nulls: true
        jdbc-type-for-null: 'null'
wechat:
  open:
    wechatOpenAuthorizeUrl: http://z5os29qr.xiaomy.net